"""add product price and image

Revision ID: c2f99dd0288b
Revises: 7a82d506ded7
Create Date: 2020-12-20 13:04:16.205726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2f99dd0288b'
down_revision = '7a82d506ded7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('price_cents', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('price_cents')
        batch_op.drop_column('picture_url')

    # ### end Alembic commands ###
